config/routes.rb
Rails.application.routes.draw do


  resources :patients, only: [:show, :index, :edit, :update]

  resources :case_books, only: [:index]

  resources :records, only: [:show, :index] do

    resource :pages, only: [:show], controller: :records, action: :pages
    resource :pages, only: [:update], controller: :records, action: :update_pages


    resource :index, only: [:show], controller: :records, action: :index_pages, as: 'index' do
      resources :index_page, only: [:show], controller: :records, action: :index_page, path: '', as: 'page'
      resources :index_page, only: [:update], controller: :records, action: :update_index_page, path: '', as: 'page'
    end
  end

  resources :case_notes, only: [:show, :destroy]

  root to: "home#show"

end

app/models/case_note.rb
class CaseNote < ApplicationRecord

  belongs_to :stay
  belongs_to :record
  belongs_to :patient
  belongs_to :index_image, class_name: :Image

end

app/controllers/case_notes_controller.rb
class CaseNotesController < ApplicationController

  def show
    @case_note = CaseNote.find(params[:id])
  end

  def destroy
    case_note = CaseNote.find(params[:id])
    record = case_note.record
    index_image = case_note.index_image

    case_note.destroy


    if index_image
      redirect_to record_index_page_path(record, index_image.id)
    else
      redirect_to record_index_path(record)
    end

  end

end

app/views/case_notes/show.html.erb
<h1>Case note link</h1>

<p>Patient: <%= link_to @case_note.patient.name, patient_path(@case_note.patient) %></p>
<p>Reference: <%= link_to "Volume #{@case_note.record.volume}", record_path(@case_note.record) %>, Page <%= @case_note.transcribed_index_page_ref %> </p>

<%= form_for @case_note, method: :delete, html: {class: 'delete'} do |form| %>
  <button type="submit">Delete</button>
<% end %>

<% if @case_note.index_image %>
  <% x = (@case_note.index_side == 'left' ? 0 : 49) %>
  <%= image_tag cropped_image_path(@case_note.index_image.id, 2048, 2048, x, 0, 51, 100) %>
<% end %>

<% if @case_note.sequence_start %>
  <% image = @case_note.record.images.find_by(sequence: @case_note.sequence_start) %>
  <%= image_tag image_path(image.id, 1024, 1024) %>
<% end %>