config/routes.rb
Rails.application.routes.draw do


  resources :patients, only: [:show, :index, :edit, :update]

  resources :case_books, only: [:index]

  resources :records, only: [:show, :index] do

    resource :pages, only: [:show], controller: :records, action: :pages
    resource :pages, only: [:update], controller: :records, action: :update_pages


    resource :index, only: [:show], controller: :records, action: :index_pages, as: 'index' do
      resources :index_page, only: [:show], controller: :records, action: :index_page, path: '', as: 'page'
      resources :index_page, only: [:update], controller: :records, action: :update_index_page, path: '', as: 'page'
    end
  end

  resources :case_notes, only: [:show, :destroy]

  root to: "home#show"

end

app/models/record.rb
require 'open-uri'
require 'json'

class Record < ApplicationRecord

  has_many :images
  has_many :case_notes


  def volume=(volume_string)
    puts "Volume: #{volume_string}"
    write_attribute(:volume, volume_string)
    write_attribute(:volume_number,volume_string.to_i) if volume_string =~ /\A\d+\z/
  end

  def update_images

    file = open("http://wellcomelibrary.org/iiif/#{id}/manifest").read

    json = JSON.parse(file)

    json['sequences'][0]['canvases'].each_with_index do |canvas, index|

      width = canvas.fetch('width')
      height = canvas.fetch('height')

      image_id = canvas['images'].first['@id'].gsub("http://wellcomelibrary.org/iiif/#{id}/imageanno/", '')


      image = images.find_or_initialize_by(id: image_id)
      image.width = width
      image.height = height
      image.sequence = index + 1
      image.save!


    end


  end

  def update_pages_with_type_count!
    self.pages_with_type = images.where.not(page_type: nil).count
    save!
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController


  def index
    @records = Record.order(:volume_number)
      .joins(:images)
      .group('records.id')
      .select('records.*, count(images.id) as images_count')
  end

  def show
    @record = Record.find(params[:id])
    @images = @record.images.order(:sequence)

    @case_notes = @record.case_notes
  end

  def pages
    @record = Record.find(params[:record_id])
    @images = @record.images.order(:sequence)
  end

  def index_pages
    @record = Record.find(params[:record_id])
    @images = @record.images.where(page_type: 'Index').order(:sequence)
    @transcribed_images = @images.select(&:transcribed).length
  end

  def index_page
    @record = Record.find(params[:record_id])
    @image = @record.images.find(params[:id])

    @case_notes = @record.case_notes.where(index_image: @image)

    @patients = Patient.order(:name)
  end

  def update_pages

    record = Record.find(params[:record_id])

    images = record.images

    params[:page].each_pair do |page, values|

      image = images.detect {|image| image.sequence == page.to_i }

      if values['left'].present?
        image.left_page = values['left']
      end

      if values['right'].present?
        image.right_page = values['right']
      end

      if values['type'].present?
        image.page_type = values['type']
      end

      image.save!

    end

    record.update_pages_with_type_count!

    redirect_to record_path(record)
  end


  def update_index_page
    record = Record.find(params[:record_id])
    image = record.images.find(params[:id])

    image.transcribed = params[:image][:transcribed]
    image.save!

    params[:index_ref].each do |index_ref|

      if index_ref[:patient_id].present? && index_ref[:page_ref].present? && index_ref[:index_side].present?

        patient = Patient.find(index_ref[:patient_id])

        index_ref[:page_ref].to_s.split(',').each do |page_number|

          start_page_image =
            record.images.where(left_page: page_number).order(:sequence).first ||
            record.images.where(right_page: page_number).order(:sequence).first

          case_note = record.case_notes.new
          case_note.index_image = image
          case_note.patient = patient


          if start_page_image
            case_note.sequence_start = start_page_image.sequence
            case_note.sequence_end = start_page_image.sequence
          end

          case_note.transcribed_index_page_ref = page_number
          case_note.index_side = index_ref[:index_side]
          case_note.save!

        end

      end


    end


    next_image = record.images.find_by(sequence: image.sequence + 1)


    if params[:next].to_s == "reload"
      redirect_to record_index_page_path(record, image.id)

    else
      if next_image.page_type == 'Index'
        redirect_to record_index_page_path(record, next_image.id)
      else
        redirect_to record_index_path(record)
      end
    end
  end

end

app/views/records/index.html.erb
<h1>Records</h1>


<ul>
  <% @records.each do |record| %>
    <li>
      <%= link_to "Vol #{record.volume} (#{record.id})", record_path(record) %>

      <%= number_to_percentage(record.pages_with_type.to_f * 100 / record.images_count, precision: 1) %> done
    </li>
  <% end %>
</ul>

app/views/records/index_page.html.erb
<h1><%= link_to "Volume #{@record.volume}", @record %> / <%= link_to "Index", record_index_path(@record) %> / <%= "#{@image.left_page.to_s.upcase} – #{@image.right_page.to_s.upcase}" %></h1>



<%= form_for @image, url: record_index_page_path(@record, @image), method: :put do |form| %>

  <% {left: @image.left_page.to_s.upcase, right: @image.right_page.to_s.upcase}.each_pair do |position, page_ref| %>


    <h2><%= page_ref %></h2>

    <table class="transcribe-index">
      <thead>
        <tr>
          <th>Patient</th>
          <th>Page ref</th>
          <th></th>
        </tr>
      </thead>


      <tbody>

        <% @case_notes.select {|cn| cn.index_side == position.to_s }.each do |case_note| %>

          <tr>
            <td><%= link_to case_note.patient.name, patient_path(case_note.patient) %></td>
            <td>
              <%= case_note.transcribed_index_page_ref %>
              <% if !case_note.sequence_start %>
                 <span class="warning">Couldn’t find page</span>
              <% end %>
            </td>
            <td>
              <%= link_to 'Delete', case_note_path(case_note), class: 'delete' %>
            </td>
          </tr>
        <% end %>

        <% 5.times do %>

          <tr>
            <td>
              <select name="index_ref[][patient_id]">
                <option></option>
                <% @patients.select {|p| p.name.upcase.start_with?(page_ref) }.each do |patient| %>
                  <option value="<%= patient.id %>">
                    <%= patient.name %>

                    <% if patient.years_string %>
                      (<%= patient.years_string %>)
                    <% end %>

                  </option>
                <% end %>

                <option>–––––</option>
                <% @patients.select {|p| !p.name.upcase.start_with?(page_ref) }.each do |patient| %>
                  <option value="<%= patient.id %>"><%= patient.name %>

                    <% if patient.years_string %>
                      (<%= patient.years_string %>)
                    <% end %>

                  </option>
                <% end %>
              </select>
            </td>
            <td colspan="2">
              <input name="index_ref[][page_ref]" type="text">
              <input name="index_ref[][index_side]" type="hidden" value="<%= position %>">
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>


    <% x = (position == :left ? 0 : 49) %>
    <%= image_tag cropped_image_path(@image.id, 2048, 2048, x, 0, 51, 100) %>

  <% end %>

  <div>
    <%= form.label :transcribed, "Page completed?" %>
    <%= form.check_box :transcribed %>
  </div>

  <div class="save-buttons">
    <button type="submit" name="next" value="next">Save &amp; Next</button>
    <button type="submit" name="next" value="reload">Save &amp; Reload</button>
  </div>

<% end %>

app/views/records/index_pages.html.erb
<h1>Index for <%= link_to "Volume #{@record.volume}", record_path(@record) %></h1>


<p>Status: <%= number_to_percentage(@transcribed_images.to_f / @images.length * 100, precision: 1) %> transcribed.</p>

<ol class="toc">

  <% @images.each do |image| %>

    <li>
      <%= link_to "#{image.left_page.upcase} – #{image.right_page.upcase}", record_index_page_path(@record, image) %> <%= 'DONE' if image.transcribed %>
    </li>
  <% end %>

</ol>

app/views/records/pages.html.erb
<h1>Page index for <%= link_to @record.id, @record %></h1>


<% page_types = ['Front Cover', 'Front Matter', 'Title', 'Index', 'Content', 'Spine', 'Inside Front Cover', 'Inside Back Cover', 'Back Cover', 'Blank'] %>

<%= form_tag record_pages_path(@record), method: :put %>

  <table class="pages js-page-number-autofill">

    <thead>
      <tr>
        <th rowspan="2" colspan="2">Thumbnail</th>
        <th colspan="2">Numbers</th>
        <th rowspan="2">Type</th>
      </tr>
      <tr>
        <th>L</th>
        <th>R</th>
      </tr>
    </thead>


    <tbody>
      <% @images.each do |image| %>

        <tr class="js-page-type-preselect">
          <td>
            <a href="<%= image_path(image.id, 2024, 2024) %>" target="_blank" tabindex="-1">
              <%= image_tag image_path(image.id, 400, 400) %>
            </a>
          </td>

          <td>
            <div><%= image_tag cropped_image_path(image.id, 200, 200, 5,3,10,10) %></div>
            <div><%= image_tag cropped_image_path(image.id, 200, 200, 90,3,10,10) %></div>
          </td>

          <td>
            <input type="text" class="page-number js-page-number" name="page[<%= image.sequence %>][left]" value="<%= image.left_page %>" id="page-input-<%= image.sequence * 2 - 1 %>"/>
          </td>

          <td>
            <input type="text" class="page-number js-page-number" name="page[<%= image.sequence %>][right]" value="<%= image.right_page %>"  id="page-input-<%= image.sequence * 2 %>"/>
          </td>

          <td>

            <select name="page[<%= image.sequence %>][type]" class="js-page-type">

              <option></option>
              <% page_types.each do |type| %>
                <option <%= 'selected' if image.page_type == type %> ><%= type %></option>
              <% end %>
            </select>

          </td>

        </tr>
      <% end %>
    </tbody>

  </table>

  <button>Save</button>
</form>

app/views/records/show.html.erb
<h1>Volume <%= @record.volume %></h1>



<p><%= link_to "Transcribe pages", record_pages_path(@record) %>       (<%= number_to_percentage(@record.pages_with_type.to_f * 100 / @record.images.count, precision: 1) %> done)</p>



<% current_sequence_start_image = @images[0] %>
<% previous_image_type = nil %>
<% previous_page_ref = nil %>
<% current_page_ref = nil %>
<% previous_image = nil %>


<h2>Contents </h2>
<ol class="toc">
  <% @images.each do |image| %>

    <% if image.page_type != previous_image_type %>

      <% if previous_image_type != nil %>
        <li>

          <% page_range = previous_image_type %>
          <% if current_page_ref.present? || previous_page_ref.present? %>
            <% page_range += " (#{current_page_ref.upcase} - #{previous_page_ref.upcase})" %>
          <% end %>

          <% if previous_image_type == 'Index' %>
            <%= link_to page_range, record_index_path(@record) %>
          <% else %>
            <%= page_range %>
          <% end %>

          <% if previous_image_type == 'Index' || previous_image_type == 'Content' %>
            <ol>
              <% current_sequence_start_image.sequence.upto(previous_image.sequence) do |sequence| %>

                <% sub_image = @images.detect {|i| i.sequence == sequence} %>

                <li>
                  <%= "#{sub_image.left_page.to_s.upcase} - #{sub_image.right_page.to_s.upcase}" %>

                  <%= @case_notes.select {|c| c.sequence_start == sub_image.sequence }.collect do |case_note| %>

                      <% case_note.stay ? case_note.stay.patient.name : case_note.patient.name %>
                  <% end.join(', ') %>

                </li>
              <% end %>
            </ol>
          <% end %>

        </li>

      <% end %>

      <% current_sequence_start_image = image %>

      <% current_page_ref = image.left_page || image.right_page || "" %>
    <% end %>

    <% previous_image_type = image.page_type %>
    <% previous_image = image %>
    <% previous_page_ref = image.right_page || image.left_page || "" %>
  <% end %>
</ol>