config/routes.rb
Rails.application.routes.draw do


  resources :patients, only: [:show, :index, :edit, :update]

  resources :case_books, only: [:index]

  resources :records, only: [:show, :index] do

    resource :pages, only: [:show], controller: :records, action: :pages
    resource :pages, only: [:update], controller: :records, action: :update_pages


    resource :index, only: [:show], controller: :records, action: :index_pages, as: 'index' do
      resources :index_page, only: [:show], controller: :records, action: :index_page, path: '', as: 'page'
      resources :index_page, only: [:update], controller: :records, action: :update_index_page, path: '', as: 'page'
    end
  end

  resources :case_notes, only: [:show, :destroy]

  root to: "home#show"

end

app/models/patient.rb
class Patient < ApplicationRecord

  has_many :stays
  has_many :case_notes

  def update_dates!

    self.first_admitted ||= stays.order(:admission).first.try(:admission)
    self.last_discharged ||= stays.order(:discharge).last.try(:discharge)
    save!

  end

  def update_length_of_stays!

    length = 0

    stays.each do |stay|

      if stay.admission && stay.discharge
        length += (stay.discharge - stay.admission) + 1
      end

    end

    if length > 0

      self.length_of_stays = length
      self.save!
    end



  end

  def years_string

    start_year = first_admitted.try(:year)
    end_year = last_discharged.try(:year)

    if start_year || end_year

      if start_year != end_year
        "#{start_year}-#{end_year}"
      else
        start_year.to_s
      end

    end


  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController


  def index

    @name_search = params[:name]
    @name_search = nil if params[:name].blank?

    stays = Stay.joins(:patient)
      .select('patients.*, stays.*')


    case params[:order].to_s
    when "admission"
      stays = stays.order('patients.highlighted desc', 'patients.first_admitted')
    when "discharged"
      stays = stays.order('patients.highlighted desc', 'patients.last_discharged')
    when "length_of_stays"
      stays = stays.order('patients.highlighted desc', '(patients.length_of_stays is null)', 'patients.length_of_stays desc')

    else
      stays = stays.order('patients.highlighted desc', 'patients.name', 'stays.admission')
    end

    if @name_search
      stays = stays.where("lower(patients.name) LIKE ?", "%#{@name_search.downcase}%")
    end

    @patients = stays.group_by(&:patient_id)


  end

  def show
    @patient = Patient.find(params[:id])
    @stays = @patient.stays.order(:admission)

    @case_notes = @patient.case_notes
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])

    introduction = params[:patient][:introduction]

    if introduction

      if !introduction.blank?
        @patient.introduction = introduction
      else
        @patient.introduction = nil
      end
    end

    @patient.save!
    redirect_to patient_path(@patient)

  end

end

app/views/patients/edit.html.erb
<h1>Edit <%= link_to @patient.name, @patient %></h1>

<%= form_for @patient do |form| %>

  <div>
    <div><%= form.label :introduction, "Introduction" %></div>
    <%= form.text_area :introduction, rows: 10, cols: 50 %>
  </div>

  <button type="submit">Save</button>


<% end %>

app/views/patients/index.html.erb
<h1>Patients</h1>

<p>We have records of <strong><%= pluralize @patients.size, 'patient' %></strong> admitted to Ticehurst from 1792 to 1917.</p>

<div class="table-search">
  <form>
    <input type="search" name="name" value="<%= @name_search %>">
    <button type="submit">Search</button>
  </form>
</div>

<table class="patients">
  <thead>
    <tr>
      <th class="name" rowspan="2"><%= link_to "Name", patients_path(order: 'name') %></th>
      <th rowspan="2"><%= link_to "Length&#160;of&#160;stay".html_safe, patients_path(order: 'length_of_stays') %></th>
      <th>

        <% order = params[:order].to_s == 'admission' ? 'discharged' : 'admission' %>

        <%= link_to "Stay Dates", patients_path(order: order) %>
      </th>
    </tr>
    <tr>
      <td>
        <svg viewbox="0 0 500 20" width="500" height="20">



          <% start_year = 1792 %>
          <% end_year = 1989 %>
          <% width_scale = 500 / (end_year - start_year) %>

          <rect x="0" y="0" width="1" height="20" fill="grey"></rect>
          <text x="3" y="15" fill="black"><%= start_year %></text>

          <rect x="499" y="0" width="1" height="20" fill="grey"></rect>
          <text x="495" y="15" fill="black" text-anchor="end"><%= end_year %></text>

          <rect x="70" y="0" width="20" height="20" fill="black"></rect>
          <text x="94" y="15" fill="black">Died</text>

          <rect x="170" y="0" width="20" height="20" fill="red"></rect>
          <text x="194" y="15" fill="black">Not improved</text>


          <rect x="340" y="0" width="20" height="20" fill="green"></rect>
          <text x="364" y="15" fill="black">'Cured'</text>


        </svg>

      </td>
    </tr>
  </thead>


  <% @patients.each do |group| %>

    <% patient = group[1][0] %>
     <tr <% if patient.highlighted %>class="highlighted" <% end %>>
      <td>
        <%= link_to patient.name, patient_path(patient.patient_id) %>
      </td>
      <td>

        <% if patient.length_of_stays %>

          <% if patient.length_of_stays > 365.25 %>


            <% years = (patient.length_of_stays.to_f / 365.25).floor %>
            <%= pluralize(years, 'year') %>

          <% else %>

            <%= pluralize(patient.length_of_stays, 'day') %>

          <% end %>

        <% else %>
          <%= pluralize(patient.stays_count, 'stay') %>
        <% end %>
      </td>

      <td>

        <svg viewbox="0 0 500 20" width="500" height="20">

          <% start_date = Date.new(1792,1,1) %>
          <% end_date = Date.new(1989,12,31) %>
          <% width_scale = 500.0 / (end_date - start_date).to_i %>


          <% dates = group[1].each do |stay| %>
            <% if stay.admission && stay.discharge %>

              <% fill = 'grey' %>
              <% case stay.transcribed_subsequent_condition.to_s.downcase
              when 'died'
                fill = 'black'
              when 'recovered', 'improved', 'cured'
                fill = 'green'
              when 'not imp.'
                fill = 'red'
              end
              %>
              <rect x="<%= (stay.admission - start_date) * width_scale %>" y="0" width="<%= ((stay.discharge - stay.admission)).to_i * width_scale  %>" height="20" fill="<%= fill %>" title="Test" />

            <% end %>
          <% end %>

        </svg>


        <% dates = group[1].collect do |stay| %>
          <%# stay_date(stay.admission, stay.transcribed_date_of_admission).to_s + " – " + stay_date(stay.discharge, stay.transcribed_date_of_discharge).to_s %>
        <% end %>

        <%#= dates.join(', ') %>
      </td>


    </tr>

  <% end %>

</table>

app/views/patients/show.html.erb
<div><%= link_to "Patient Index", patients_path %></div>

<h1><%= @patient.name %></h1>

<% if @patient.introduction %>
  <div class="introduction">
    <p><%= @patient.introduction.html_safe %></p>
  </div>
<% end %>

<ol class="toc">
  <% @patient.stays.each do |stay| %>

    <li>
      <a href="#stay-<%= stay.id %>"><%= stay.transcribed_date_of_admission %> – <%= stay.transcribed_date_of_discharge %></a>

      <ol>
        <% if stay.admission_certificate %>
          <li><a href="#stay-<%= stay.id %>-admission">Admission certificate</a></li>
        <% end %>

        <% if stay.case_notes.size > 0 %>
          <li><a href="#stay-<%= stay.id %>-case-notes">Case Notes</a></li>
        <% end %>

        <% if stay.discharge_note %>
          <li><a href="#stay-<%= stay.id %>-discharge">Discharge/Death Note</a></li>
        <% end %>

        <% if stay.bill_notes.size > 0 %>
          <li><a href="#stay-<%= stay.id %>-bills">Bills</a></li>
        <% end %>
      </ol>

    </li>

  <% end %>

  <% if @case_notes.size > 0 %>
    <li><a href="#misc-case-notes">Case Notes</a></li>
  <% end %>

</ol>

<table>

  <thead>
    <tr>
      <th>Date of Admission</th>
      <th>Date of Discharge</th>
      <th>Subsequent condition</th>
      <th>[Archives Ref]</th>
      <th>[Index file ref]</th>
    </tr>

  </thead>

  <% @stays.each do |stay| %>

    <tr>
      <td>
        <%= stay.transcribed_date_of_admission %>
      </td>

      <td>
        <%= stay.transcribed_date_of_discharge %>
      </td>

      <td>
        <%= stay.transcribed_subsequent_condition %>
      </td>

      <td>
        <%= stay.transcribed_archives_ref %>
      </td>

      <td>
        P<%= stay.transcribed_page %> L<%= stay.transcribed_line %>
      </td>

    </tr>

  <% end %>
</table>


<% @patient.stays.each do |stay| %>

  <h2 id="stay-<%= stay.id %>"><%= stay.transcribed_date_of_admission %> - <%= stay.transcribed_date_of_discharge %></h2>

  <% if stay.admission_certificate %>

    <% record = stay.admission_certificate.record %>

    <h3 id="stay-<%= stay.id %>-admission">Admission Certificate</h3>

    <% stay.admission_certificate.sequence_start.upto(stay.admission_certificate.sequence_end) do |sequence| %>

      <% image = record.images.find_by(sequence: sequence) %>

      <%= image_tag image_path(image.id, 1024, 1024) %>

    <% end %>

  <% end %>

  <% if stay.case_notes.size > 0 %>

    <h3 id="stay-<%= stay.id %>-case-notes">Case Notes</h3>


    <% stay.case_notes.each do |case_note| %>

      <% record = case_note.record %>

      <% case_note.sequence_start.upto(case_note.sequence_end) do |sequence| %>

        <% image = record.images.find_by(sequence: sequence) %>

        <%= image_tag image_path(image.id, 1024, 1024) %>

      <% end %>

    <% end %>
  <% end %>


  <% if stay.discharge_note %>

    <% record = stay.discharge_note.record %>

    <h3 id="stay-<%= stay.id %>-discharge">Discharge/Death Note</h3>

    <% stay.discharge_note.sequence_start.upto(stay.discharge_note.sequence_end) do |sequence| %>

      <% image = record.images.find_by(sequence: sequence) %>

      <%= image_tag image_path(image.id, 1024, 1024) %>

    <% end %>

  <% end %>

  <% if stay.bill_notes.size > 0 %>

    <h3 id="stay-<%= stay.id %>-bills">Bills</h3>


    <% stay.bill_notes.each do |bill_note| %>

      <% record = bill_note.record %>

      <% bill_note.sequence_start.upto(bill_note.sequence_end) do |sequence| %>

        <% image = record.images.find_by(sequence: sequence) %>

        <%= image_tag image_path(image.id, 1024, 1024) %>

      <% end %>

    <% end %>
  <% end %>

<% end %>

<% if @case_notes.size > 0 %>

  <h3 id="misc-case-notes">Case Notes</h3>


  <% @case_notes.each do |case_note| %>

    <% record = case_note.record %>

    <% if case_note.sequence_start %>

      <% case_note.sequence_start.upto(case_note.sequence_end) do |sequence| %>

        <% image = record.images.find_by(sequence: sequence) %>

        <%= image_tag image_path(image.id, 1024, 1024) %>

      <% end %>
    <% end %>

  <% end %>
<% end %>